server:
  port: 9002

spring:
  application:
    name: lost-found-service
  datasource:
    url: jdbc:h2:mem:campus_platform;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-local.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

qiniu:
  enabled: false
  prefix:
    lost-found: lost-found/
    product: product/
    avatar: avatar/
    activity: activity/

upload:
  local-dir: uploads-local

eureka:
  client:
    enabled: false
